Empty deps array added in AMD distributions, v0.1.16
This should not be needed but require.js optimizer seems not to enjoy
running on AMD distributions of Woodman when they start with:
 define(function () { ... })
... instead of:
 define([], function () { ... })

I do not know why it fails without the empty array or why it actually
suceeds with the array for that matter. Using a command such as:

 node_modules/requirejs/bin/r.js -o name=dist/woodman-amd.js
    baseUrl=. out=test.js

on the distribution file when it does not define an empty deps array
yields:

 TypeError: Cannot read property '1' of undefined
   at [path to requirejs]/bin/r.js:20197:111